version: '3'

volumes:
  postgres:
  pgadmin:

services:
  # docker exec -it postgres psql -U postgres -d app
  #  -U -> being the username
  #  -d -> being the database
  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'

  pgadmin:
      # http://localhost:5050
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@localhost.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 5050
        PGADMIN_CONFIG_SERVER_MODE: "False"
        PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      volumes:
        - pgadmin:/var/lib/pgadmin
        # see docker_pgadmin_servers.json in the under root dir
        - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
      ports:
        - "5050:5050"
      entrypoint:
        - "/bin/sh"
        - "-c"
        - "/bin/echo 'postgres:5432:*:postgres:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
      depends_on:
        - postgres